[versions]
kotlin = "2.3.20"
detekt = "1.23.8"
git-hooks = "0.0.2"

kord-extensions = "2.4.1-20251224.130127-1"
kordex-plugin = "1.9.2"
logging = "8.0.01"
logback = "1.5.23"
mongo = "5.6.5"

# Keep this the same as KordEx
ktor = "3.2.3"

[libraries]
kord-extensions-core = { module = "dev.kordex:kord-extensions", version.ref = "kord-extensions" }
kord-extensions-unsafe = { module = "dev.kordex.modules:dev-unsafe", version.ref = "kord-extensions"}

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.oshai:kotlin-logging", version.ref = "logging" }
mongodb = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongo" }
mongodb-driverkx = { module = "org.mongodb:mongodb-driver-kotlin-extensions", version.ref = "mongo" }
bsonkx = { module = "org.mongodb:bson-kotlinx", version.ref = "mongo" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt"}
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
git-hooks = { id = "com.github.jakemarsden.git-hooks", version.ref = "git-hooks" }
kord-extensions-plugin = { id = "dev.kordex.gradle.kordex", version.ref = "kordex-plugin"}
